//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmisionPS2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PACIENTE
    {
        public int P_RUTPACIENTE { get; set; }
        public string P_PATERNO { get; set; }
        public string P_MATERNO { get; set; }
        public string P_NOMBRE { get; set; }
        public Nullable<bool> P_SEXO { get; set; }
        public Nullable<System.DateTime> P_FECHANAC { get; set; }
        public string P_PREVISION { get; set; }
        public string P_DIRECCION { get; set; }
        public string C_IDCOMUNA { get; set; }
        public string P_FONOPAR { get; set; }
        public string P_FONOLAB { get; set; }
        public string P_CELULAR { get; set; }
        public string P_EMAIL { get; set; }
        public string P_USUARIOAUD { get; set; }
        public Nullable<System.DateTime> P_FECHAAUD { get; set; }
        public string P_HOSTAUD { get; set; }
        public string p_CIUDAD { get; set; }
        public string P_Area { get; set; }
        public string C_IDCIUDAD { get; set; }
        public string C_CODIGOAREA { get; set; }
        public string RESPUESTAWEB { get; set; }
        public string PREGUNTAWEB { get; set; }
        public string CLAVEWEB { get; set; }
        public string p_hijomedico { get; set; }
        public string tipodocu { get; set; }
        public string OCUPACION { get; set; }
        public string CONTACTO { get; set; }
    }
}
